import i18next from "i18next";
import { Type } from "#app/data/type";
import { TrainerType } from "#enums/trainer-type";
import { Species } from "#enums/species";
import { Abilities } from "#enums/abilities";
import { FormChangeItem } from "#enums/form-change-items";
import { UpgradePath } from "#enums/upgrade-path";
import { Moves } from "#enums/moves";
import { PlayableChampionData, SkillCategory } from "#app/system/playable-champions";
import { PokemonAltBuildId } from "#app/data/pokemon-alt-buid";
import { SkillTreeRewardType } from "#app/system/skill-tree-data";
import { QuestUnlockables } from "#app/system/game-data.js";
import { VoucherType } from "#app/system/voucher";
export const CHAMPION_DEFINITIONS: Record<string, Partial<PlayableChampionData>> = new Proxy({} as Record<string, Partial<PlayableChampionData>>, {
  get(target, prop: string | symbol) {
    const propKey = prop as string;

    if (propKey === "apollo" || propKey === "diana") {
      const baseKey = "apollo_diana";
      if (!_CHAMPION_DEFINITIONS) {
        initializeChampionDefinitions();
      }
      if (!(baseKey in target)) {
        target[baseKey] = _CHAMPION_DEFINITIONS[baseKey];
      }
      const baseDefinition = target[baseKey];
      if (!baseDefinition) {
        return undefined;
      }

      const uiOverrides = propKey === "apollo"
        ? { skillTreeRootOffsetX: -5, skillTreeRootOffsetY: -7 }
        : { skillTreeRootOffsetX: 0, skillTreeRootOffsetY: -1, skillTreeTrainerBondOffsetX: 0 };

      return {
        ...baseDefinition,
        id: propKey,
        ui: {
          ...baseDefinition.ui,
          ...uiOverrides
        }
      };
    }

    if (!(propKey in target)) {
      if (!_CHAMPION_DEFINITIONS) {
        initializeChampionDefinitions();
      }
      target[propKey] = _CHAMPION_DEFINITIONS[propKey as keyof Record<string, Partial<PlayableChampionData>>];
    }
    return target[propKey];
  }
});

let _CHAMPION_DEFINITIONS: Record<string, Partial<PlayableChampionData>> | null = null;

export function initializeChampionDefinitions(): Record<string, Partial<PlayableChampionData>> {
  if (_CHAMPION_DEFINITIONS !== null) {
    return _CHAMPION_DEFINITIONS;
  }
  _CHAMPION_DEFINITIONS = {
    apollo_diana: {
      id: "apollo_diana",
      type1: Type.UNKNOWN,
      ui: {
        previewOffsetY: -20,
        previewScale: 0.42,
        gridOffsetY: 0,
        gridScale: 0.12,
        skillTreeRootOffsetX: -5,
        skillTreeRootOffsetY: -5,
        skillTreeTrainerBondScale: 0.5,
        skillTreeTrainerBondOffsetX: -2,
        skillTreeTrainerBondOffsetY: 0,
      },
      signaturePokemon: [Species.SOLROCK, Species.LUNATONE],
      legendaryPokemon: [Species.LUNALA],
      pokemonGenerationFilter: [],

      unlockedTMs: [],
      unlockedXMs: [],
      unlockedAbilities: [],
      unlockedSmittyAbilities: [Abilities.SUN_AND_MOON],
      unlockedMegaStones: [FormChangeItem.LUCARIONITE],
      unlockedGlitchForms: ["wispeeon"],
      glitchFormUnlockableIds: { "wispeeon": QuestUnlockables.EEVEE_GHOST_QUEST },
      unlockedPermaItems: [],
      unlockedStatBoosts: [],
      unlockedAltBuilds: [PokemonAltBuildId.SOLROCK_VOID_CONSTELLATION],
      unlockedConditionalAbilities: [Abilities.BLAZE],
      unlockedVoucherTiers: [VoucherType.REGULAR, VoucherType.PLUS, VoucherType.PREMIUM],
      unlockedSpecificPermaModifiers: [],
      unlockedMoveUpgrades: [UpgradePath.POWER_1],
      unlockedTypeSwitchers: [],
      unlockedEssenceBundles: [],
      unlockedTypeBoosters: [],
      unlockedTeraTypes: [],
      unlockedMoneyReward: true,
      unlockedPermaMoney: true,
      unlockedBallRaritySelect: { rogue: true, master: true },

      unlockedHealingItems: true,
      unlockedMemoryMushroom: true,
      unlockedBerries: true,
      unlockedAbilitySwitchers: true,
      unlockedGeneralItems: true,
      unlockedBaton: true,
      unlockedPPMax: true,
      unlockedRogueBall: true,
      unlockedGoldenPokeball: true,
      unlockedMasterBall: true,

      unlockRequirements: {
        essenceRequirements: [],
        totalEssenceRequirement: 0,
        description: "Available from start"
      },

      lockedSkills: {
        level_2: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 2,
          prerequisites: { all: ["start"] },
          unlockableId: FormChangeItem.CHARIZARDITE_Y,
        },
        level_3: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 3,
          prerequisites: { all: ["level_2"] },
          unlockableId: Abilities.FLAME_BODY,
        },
        level_4: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 4,
          prerequisites: { all: ["level_3"] },
          unlockableId: Abilities.INTIMIDATE,
        },
        level_5: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 5,
          prerequisites: { all: ["level_4"] },
          unlockableId: Abilities.REGENERATOR_PLUS,
        },
        level_6: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 6,
          prerequisites: { all: ["level_5"] },
          unlockableId: Species.XERNEAS,
        },
        level_7: {
          category: SkillCategory.POKEMON_ALT_BUILDS,
          rewardType: SkillTreeRewardType.POKEMON_ALT_BUILD,
          unlockLevel: 7,
          prerequisites: { all: ["level_6"] },
          unlockableId: PokemonAltBuildId.LUNATONE_DREAM_WEAVER,
        },
        level_8: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 8,
          prerequisites: { all: ["level_7"] },
          unlockableId: Abilities.SHADOW_TAG,
        },
        level_9: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 9,
          prerequisites: { all: ["level_8"] },
          unlockableId: Abilities.CHARRED_MEMORY,
        },
        level_10: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 10,
          prerequisites: { all: ["level_9"] },
          unlockableId: Species.EEVEE,
        },
        level_11: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 11,
          prerequisites: { all: ["level_10"] },
          unlockableId: FormChangeItem.CHANDELURITE,
        },
        level_12: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 12,
          prerequisites: { all: ["level_11"] },
          unlockableId: Abilities.STALWART,
        },
        level_13: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 13,
          prerequisites: { all: ["level_12"] },
          unlockableId: Abilities.SUNBATHER,
        },
        level_14: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 14,
          prerequisites: { all: ["level_13"] },
          unlockableId: Species.MOLTRES,
        },
        level_15: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 15,
          prerequisites: { all: ["level_14"] },
          unlockableId: QuestUnlockables.MAGICAL_PIKACHU_QUEST,
        },
        level_16: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 16,
          prerequisites: { all: ["level_15"] },
          unlockableId: Abilities.STAKEOUT,
        },
        level_17: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 17,
          prerequisites: { all: ["level_16"] },
          unlockableId: Abilities.FLAMING_CHAKRA,
        },
        level_18: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 18,
          prerequisites: { all: ["level_17"] },
          unlockableId: Species.LITWICK,
        },
        level_19: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 19,
          prerequisites: { all: ["level_18"] },
          unlockableId: FormChangeItem.CHANDELURITE,
        },
        level_20: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 20,
          prerequisites: { all: ["level_19"] },
          unlockableId: Abilities.HUSTLE,
        },
        level_21: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 21,
          prerequisites: { all: ["level_20"] },
          unlockableId: Abilities.PLAGUE_PSYCHE,
        },
        level_22: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 22,
          prerequisites: { all: ["level_21"] },
          unlockableId: Species.JIRACHI,
        },
        level_23: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 23,
          prerequisites: { all: ["level_22"] },
          unlockableId: Abilities.QUICK_FEET,
        },
        level_24: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 24,
          prerequisites: { all: ["level_23"] },
          unlockableId: Abilities.EIGHT_BIT_BLAZE,
        },
        level_25: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 25,
          prerequisites: { all: ["level_24"] },
          unlockableId: Species.SWABLU,
        },
        level_26: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 26,
          prerequisites: { all: ["level_25"] },
          unlockableId: FormChangeItem.CLEFABLITE,
        },
        level_27: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 27,
          prerequisites: { all: ["level_26"] },
          unlockableId: Abilities.RIVALRY,
        },
        level_28: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 28,
          prerequisites: { all: ["level_27"] },
          unlockableId: Abilities.SOLAR_POWER_PLUS,
        },
        level_29: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 29,
          prerequisites: { all: ["level_28"] },
          unlockableId: Species.NECROZMA,
        },
        level_30: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 30,
          prerequisites: { all: ["level_29"] },
          unlockableId: QuestUnlockables.EEVEE_STEEL_QUEST,
        },
        level_31: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 31,
          prerequisites: { all: ["level_30"] },
          unlockableId: Abilities.MOXIE,
        },
        level_32: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 32,
          prerequisites: { all: ["level_31"] },
          unlockableId: Abilities.TOXIC_COMBUSTION,
        },
        level_33: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 33,
          prerequisites: { all: ["level_32"] },
          unlockableId: Species.SUNKERN,
        },
        level_34: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 34,
          prerequisites: { all: ["level_33"] },
          unlockableId: FormChangeItem.ALTARIANITE,
        },
        level_35: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 35,
          prerequisites: { all: ["level_34"] },
          unlockableId: Abilities.AURA_BREAK,
        },
        level_36: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 36,
          prerequisites: { all: ["level_35"] },
          unlockableId: Abilities.PSYCHO_FORM,
        },
        level_37: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 37,
          prerequisites: { all: ["level_36"] },
          unlockableId: Species.RESHIRAM,
        },
        level_38: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 38,
          prerequisites: { all: ["level_37"] },
          unlockableId: QuestUnlockables.CHARMANDER_UNDERTALE_QUEST,
        },
        level_39: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 39,
          prerequisites: { all: ["level_38"] },
          unlockableId: Abilities.DARK_AURA,
        },
        level_40: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 40,
          prerequisites: { all: ["level_39"] },
          unlockableId: Abilities.CLOAK_OF_SHADOWS,
        },
        level_41: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 41,
          prerequisites: { all: ["level_40"] },
          unlockableId: Species.CLEFFA,
        },
        level_42: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 42,
          prerequisites: { all: ["level_41"] },
          unlockableId: FormChangeItem.MALAMARITE,
        },
        level_43: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 43,
          prerequisites: { all: ["level_42"] },
          unlockableId: Abilities.FAIRY_AURA,
        },
        level_44: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 44,
          prerequisites: { all: ["level_43"] },
          unlockableId: Abilities.HAUNTING_BROADCAST,
        },
        level_45: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 45,
          prerequisites: { all: ["level_44"] },
          unlockableId: Species.GOUGING_FIRE,
        },
        level_46: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 46,
          prerequisites: { all: ["level_45"] },
          unlockableId: Abilities.NO_GUARD,
        },
        level_47: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 47,
          prerequisites: { all: ["level_46"] },
          unlockableId: Abilities.DEEP_THOUGHTS,
        },
        level_48: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 48,
          prerequisites: { all: ["level_47"] },
          unlockableId: Species.LARVESTA,
        },
        level_49: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 49,
          prerequisites: { all: ["level_48"] },
          unlockableId: FormChangeItem.CLEFABLITE,
        },
        level_50: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 50,
          prerequisites: { all: ["level_49"] },
          unlockableId: Abilities.SNIPER,
        },
        level_51: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 51,
          prerequisites: { all: ["level_50"] },
          unlockableId: Abilities.PREDATOR_INSTINCT,
        },
        level_52: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 52,
          prerequisites: { all: ["level_51"] },
          unlockableId: Species.VICTINI,
        },
        level_53: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 53,
          prerequisites: { all: ["level_52"] },
          unlockableId: Abilities.SOLAR_POWER,
        },
        level_54: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 54,
          prerequisites: { all: ["level_53"] },
          unlockableId: Abilities.PARENTAL_HAUNTING,
        },
        level_55: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 55,
          prerequisites: { all: ["level_54"] },
          unlockableId: Species.RIOLU,
        },
        level_56: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 56,
          prerequisites: { all: ["level_55"] },
          unlockableId: FormChangeItem.ABSOLITE,
        },
        level_57: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 57,
          prerequisites: { all: ["level_56"] },
          unlockableId: Abilities.DROUGHT,
        },
        level_58: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 58,
          prerequisites: { all: ["level_57"] },
          unlockableId: Abilities.FIRE_RAF_RAF,
        },
        level_59: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 59,
          prerequisites: { all: ["level_58"] },
          unlockableId: Species.CRESSELIA,
        },
        level_60: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 60,
          prerequisites: { all: ["level_59"] },
          unlockableId: QuestUnlockables.SOLROCK_LUNATONE_WIN_QUEST,
        },
        level_61: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 61,
          prerequisites: { all: ["level_60"] },
          unlockableId: Abilities.CHLOROPHYLL,
        },
        level_62: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 62,
          prerequisites: { all: ["level_61"] },
          unlockableId: Abilities.UNYIELDING_COURAGE,
        },
        level_63: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 63,
          prerequisites: { all: ["level_62"] },
          unlockableId: Species.CASTFORM,
        },
        level_64: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 64,
          prerequisites: { all: ["level_63"] },
          unlockableId: FormChangeItem.MALAMARITE,
        },
        level_65: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 65,
          prerequisites: { all: ["level_64"] },
          unlockableId: Abilities.FLASH_FIRE,
        },
        level_66: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 66,
          prerequisites: { all: ["level_65"] },
          unlockableId: Abilities.HAUNTING_ECHO,
        },
        level_67: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 67,
          prerequisites: { all: ["level_66"] },
          unlockableId: Species.TAPU_LELE,
        },
        level_68: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 68,
          prerequisites: { all: ["level_67"] },
          unlockableId: QuestUnlockables.CHARIZARD_HELLFLAME_QUEST,
        },
        level_69: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 69,
          prerequisites: { all: ["level_68"] },
          unlockableId: Abilities.MAGMA_ARMOR,
        },
        level_70: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 70,
          prerequisites: { all: ["level_69"] },
          unlockableId: Abilities.HAUNTING_SCYTHE,
        },
        level_71: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 71,
          prerequisites: { all: ["level_70"] },
          unlockableId: Species.TEDDIURSA,
        },
        level_72: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 72,
          prerequisites: { all: ["level_71"] },
          unlockableId: Abilities.DESOLATE_LAND,
        },
        level_73: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 73,
          prerequisites: { all: ["level_72"] },
          unlockableId: Abilities.FLAME_SPIRIT,
        },
        level_74: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 74,
          prerequisites: { all: ["level_73"] },
          unlockableId: Species.IRON_VALIANT,
        },
        level_75: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 75,
          prerequisites: { all: ["level_74"] },
          unlockableId: QuestUnlockables.ELEMENTAL_MONKEY_WIN_QUEST,
        },
        level_76: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 76,
          prerequisites: { all: ["level_75"] },
          unlockableId: Abilities.BAD_DREAMS,
        },
        level_77: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 77,
          prerequisites: { all: ["level_76"] },
          unlockableId: Abilities.ETERNAL_YOUTH,
        },
        level_78: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 78,
          prerequisites: { all: ["level_77"] },
          unlockableId: Abilities.COMATOSE,
        },
        level_79: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 79,
          prerequisites: { all: ["level_78"] },
          unlockableId: Abilities.SOUL_BURN,
        },
        level_80: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 80,
          prerequisites: { all: ["level_79"] },
          unlockableId: Species.HO_OH,
        },
        level_81: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 81,
          prerequisites: { all: ["level_80"] },
          unlockableId: QuestUnlockables.CHANDELURE_REST_QUEST,
        },
        level_82: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 82,
          prerequisites: { all: ["level_81"] },
          unlockableId: Abilities.SHADOW_SHIELD,
        },
        level_83: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 83,
          prerequisites: { all: ["level_82"] },
          unlockableId: Abilities.BLACK_AND_RED,
        },
        level_84: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 84,
          prerequisites: { all: ["level_83"] },
          unlockableId: Abilities.MOODY,
        },
        level_85: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 85,
          prerequisites: { all: ["level_84"] },
          unlockableId: Abilities.APEX_PREDATOR,
        },
        level_86: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 86,
          prerequisites: { all: ["level_85"] },
          unlockableId: Species.SOLGALEO,
        },
        level_87: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 87,
          prerequisites: { all: ["level_86"] },
          unlockableId: Abilities.PRIMORDIAL_SEA,
        },
        level_88: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 88,
          prerequisites: { all: ["level_87"] },
          unlockableId: Abilities.FLAMING_EMISSION,
        },
        level_89: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 89,
          prerequisites: { all: ["level_88"] },
          unlockableId: Abilities.PRISM_ARMOR,
        },
        level_90: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 90,
          prerequisites: { all: ["level_89"] },
          unlockableId: Abilities.HELL_FLAME,
        },
        level_91: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 91,
          prerequisites: { all: ["level_90"] },
          unlockableId: Species.SCREAM_TAIL,
        },
        level_92: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 92,
          prerequisites: { all: ["level_91"] },
          unlockableId: Abilities.NEUROFORCE,
        },
        level_93: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 93,
          prerequisites: { all: ["level_92"] },
          unlockableId: Abilities.SWIFT_CLAWS,
        },
        level_94: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 94,
          prerequisites: { all: ["level_93"] },
          unlockableId: Abilities.VICTORY_STAR,
        },
        level_95: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 95,
          prerequisites: { all: ["level_94"] },
          unlockableId: Abilities.MULTI_MIND,
        },
        level_96: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 96,
          prerequisites: { all: ["level_95"] },
          unlockableId: Species.GIRATINA,
        },
        level_97: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 97,
          prerequisites: { all: ["level_96"] },
          unlockableId: Abilities.SERENE_GRACE,
        },
        level_98: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 98,
          prerequisites: { all: ["level_97"] },
          unlockableId: Abilities.ENLIGHTENED,
        },
        level_99: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 99,
          prerequisites: { all: ["level_98"] },
          unlockableId: Abilities.SUPER_LUCK,
        },
        level_100: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 100,
          prerequisites: { all: ["level_99"] },
          unlockableId: Abilities.SLAYER_SENSEI,
        },
        level_101: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 101,
          prerequisites: { all: ["level_100"] },
          unlockableId: Species.FLUTTER_MANE,
        },
        level_102: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 102,
          prerequisites: { all: ["level_101"] },
          unlockableId: Abilities.MAGIC_GUARD,
        },
        level_103: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 103,
          prerequisites: { all: ["level_102"] },
          unlockableId: Abilities.YIN_YANG,
        },
        level_104: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 104,
          prerequisites: { all: ["level_103"] },
          unlockableId: Abilities.PSYCHIC_SURGE,
        },
        level_105: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 105,
          prerequisites: { all: ["level_104"] },
          unlockableId: Abilities.UNFAZED,
        },
        level_106: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 106,
          prerequisites: { all: ["level_105"] },
          unlockableId: Species.ENAMORUS,
        },
        level_107: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 107,
          prerequisites: { all: ["level_106"] },
          unlockableId: Abilities.DEFIANT,
        },
        level_108: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 108,
          prerequisites: { all: ["level_107"] },
          unlockableId: Abilities.FLAME_FORM,
        },
        level_109: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 109,
          prerequisites: { all: ["level_108"] },
          unlockableId: Abilities.CORRUPTION_BLAZE,
        },
        level_110: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 110,
          prerequisites: { all: ["level_109"] },
          unlockableId: Species.ENTEI,
        },
        level_111: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 111,
          prerequisites: { all: ["level_110"] },
          unlockableId: Abilities.FOX_WISDOM,
        },
        level_112: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 112,
          prerequisites: { all: ["level_111"] },
          unlockableId: Abilities.SCREEPY,
        },
        level_113: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 113,
          prerequisites: { all: ["level_112"] },
          unlockableId: Abilities.GHOSTIFY,
        },
        level_114: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 114,
          prerequisites: { all: ["level_113"] },
          unlockableId: Abilities.FAIRY_FEAR,
        },
      },
    },

    brock: {
      id: "brock",
      type1: Type.ROCK,
      type2: Type.GROUND,
      trainerType: TrainerType.BROCK,
      ui: {
        previewOffsetY: -25,
        gridOffsetY: -5,
        skillTreeRootOffsetX: 0,
        skillTreeRootOffsetY: -35,
        skillTreeTrainerBondScale: 1.1,
        skillTreeTrainerBondOffsetX: 0,
        skillTreeTrainerBondOffsetY: -15,
      },
      signaturePokemon: [Species.ONIX],
      legendaryPokemon: [Species.REGIROCK],
      pokemonGenerationFilter: [],

      unlockedTMs: [],
      unlockedXMs: [],
      unlockedAbilities: [],
      unlockedSmittyAbilities: [Abilities.ALIEN_ROCK],
      unlockedMegaStones: [FormChangeItem.STEELIXITE],
      unlockedGlitchForms: ["sudolem"],
      glitchFormUnlockableIds: { "sudolem": QuestUnlockables.SUDOWOODO_WOOD_HAMMER_QUEST },
      unlockedTypeSwitchers: [],
      unlockedEssenceBundles: [],
      unlockedPermaItems: [],
      unlockedStatBoosts: ["brock_def_boost"],
      unlockedAltBuilds: [PokemonAltBuildId.ONIX_CRYSTAL_LEVIATHAN],
      unlockedConditionalAbilities: [Abilities.BATTLE_ARMOR],
      unlockedMoveUpgrades: [UpgradePath.POWER_1],
      unlockedTypeBoosters: [],
      unlockedVoucherTiers: [VoucherType.REGULAR, VoucherType.PLUS, VoucherType.PREMIUM],
      unlockedSpecificPermaModifiers: [],
      unlockedTeraTypes: [],
      unlockedMoneyReward: true,
      unlockedPermaMoney: true,
      unlockedBallRaritySelect: { rogue: true, master: true },

      unlockedHealingItems: true,
      unlockedMemoryMushroom: true,
      unlockedBerries: true,
      unlockedAbilitySwitchers: true,
      unlockedGeneralItems: true,
      unlockedBaton: true,
      unlockedPPMax: true,
      unlockedRogueBall: true,
      unlockedGoldenPokeball: true,
      unlockedMasterBall: true,

      unlockRequirements: {
        essenceRequirements: [
          { type: Type.GROUND, amount: 75 },
          { type: Type.ROCK, amount: 75 }
        ],
        totalEssenceRequirement: 150,
        description: () => i18next.t("championSelect:brock.essenceRequirement", { ground: 75, rock: 75 })
      },
      lockedSkills: {
        level_1: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 1,
          prerequisites: { all: ["start"] },
          unlockableId: FormChangeItem.AERODACTYLITE,
        },
        level_2: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 2,
          prerequisites: { all: ["level_1"] },
          unlockableId: Abilities.ROCK_HEAD,
        },
        level_3: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 3,
          prerequisites: { all: ["level_2"] },
          unlockableId: Abilities.STURDY,
        },
        level_4: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 4,
          prerequisites: { all: ["level_3"] },
          unlockableId: Abilities.COUNTER_COAT,
        },
        level_5: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 5,
          prerequisites: { all: ["level_4"] },
          unlockableId: Species.DIANCIE,
        },
        level_6: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 6,
          prerequisites: { all: ["level_5"] },
          unlockableId: QuestUnlockables.EEVEE_GROUND_QUEST,
        },
        level_7: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 7,
          prerequisites: { all: ["level_6"] },
          unlockableId: Abilities.SOLID_ROCK,
        },
        level_8: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 8,
          prerequisites: { all: ["level_7"] },
          unlockableId: Abilities.ROCK_SOLID_MEME,
        },
        level_9: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 9,
          prerequisites: { all: ["level_8"] },
          unlockableId: Species.COMFEY,
        },
        level_10: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 10,
          prerequisites: { all: ["level_9"] },
          unlockableId: FormChangeItem.EXCADRILLITE,
        },
        level_11: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 11,
          prerequisites: { all: ["level_10"] },
          unlockableId: Abilities.SHELL_ARMOR,
        },
        level_12: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 12,
          prerequisites: { all: ["level_11"] },
          unlockableId: Abilities.ROCK_ROLL,
        },
        level_13: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 13,
          prerequisites: { all: ["level_12"] },
          unlockableId: Species.TERRAKION,
        },
        level_14: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 14,
          prerequisites: { all: ["level_13"] },
          unlockableId: QuestUnlockables.GLISCOR_DARK_MOVE_KNOCKOUT_QUEST,
        },
        level_15: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 15,
          prerequisites: { all: ["level_14"] },
          unlockableId: Abilities.FILTER,
        },
        level_16: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 16,
          prerequisites: { all: ["level_15"] },
          unlockableId: Abilities.ROCKY_HORROR_SHOW,
        },
        level_17: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 17,
          prerequisites: { all: ["level_16"] },
          unlockableId: Species.VULPIX,
        },
        level_18: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 18,
          prerequisites: { all: ["level_17"] },
          unlockableId: FormChangeItem.EXCADRILLITE,
        },
        level_19: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 19,
          prerequisites: { all: ["level_18"] },
          unlockableId: Abilities.THICK_FAT,
        },
        level_20: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 20,
          prerequisites: { all: ["level_19"] },
          unlockableId: Abilities.ROCK_CONTROL,
        },
        level_21: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 21,
          prerequisites: { all: ["level_20"] },
          unlockableId: Species.TING_LU,
        },
        level_22: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 22,
          prerequisites: { all: ["level_21"] },
          unlockableId: QuestUnlockables.REGIROCK_NIGHTMARE_QUEST,
        },
        level_23: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 23,
          prerequisites: { all: ["level_22"] },
          unlockableId: Abilities.CLEAR_BODY,
        },
        level_24: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 24,
          prerequisites: { all: ["level_23"] },
          unlockableId: Abilities.STEADY_STANCE,
        },
        level_25: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 25,
          prerequisites: { all: ["level_24"] },
          unlockableId: Species.CROAGUNK,
        },
        level_26: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 26,
          prerequisites: { all: ["level_25"] },
          unlockableId: FormChangeItem.BARBARACLITE,
        },
        level_27: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 27,
          prerequisites: { all: ["level_26"] },
          unlockableId: Abilities.WHITE_SMOKE,
        },
        level_28: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 28,
          prerequisites: { all: ["level_27"] },
          unlockableId: Abilities.DIRT_THICK,
        },
        level_29: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 29,
          prerequisites: { all: ["level_28"] },
          unlockableId: Species.IRON_THORNS,
        },
        level_30: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 30,
          prerequisites: { all: ["level_29"] },
          unlockableId: QuestUnlockables.EISCUE_ROCK_KNOCKOUT_QUEST,
        },
        level_31: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 31,
          prerequisites: { all: ["level_30"] },
          unlockableId: Abilities.FULL_METAL_BODY,
        },
        level_32: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 32,
          prerequisites: { all: ["level_31"] },
          unlockableId: Abilities.EARTH_SPEEDER,
        },
        level_33: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 33,
          prerequisites: { all: ["level_32"] },
          unlockableId: Species.MUDKIP,
        },
        level_34: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 34,
          prerequisites: { all: ["level_33"] },
          unlockableId: FormChangeItem.SWAMPERTITE,
        },
        level_35: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 35,
          prerequisites: { all: ["level_34"] },
          unlockableId: Abilities.SHADOW_SHIELD,
        },
        level_36: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 36,
          prerequisites: { all: ["level_35"] },
          unlockableId: Abilities.LIFE_ADVICE,
        },
        level_37: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 37,
          prerequisites: { all: ["level_36"] },
          unlockableId: Species.LANDORUS,
        },
        level_38: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 38,
          prerequisites: { all: ["level_37"] },
          unlockableId: QuestUnlockables.NINETALES_STORED_POWER_KNOCKOUT_QUEST,
        },
        level_39: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 39,
          prerequisites: { all: ["level_38"] },
          unlockableId: Abilities.PRISM_ARMOR,
        },
        level_40: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 40,
          prerequisites: { all: ["level_39"] },
          unlockableId: Abilities.KNIGHTS_SHOVEL,
        },
        level_41: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 41,
          prerequisites: { all: ["level_40"] },
          unlockableId: Species.HAPPINY,
        },
        level_42: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 42,
          prerequisites: { all: ["level_41"] },
          unlockableId: FormChangeItem.SKARMORYITE,
        },
        level_43: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 43,
          prerequisites: { all: ["level_42"] },
          unlockableId: Abilities.MULTISCALE,
        },
        level_44: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 44,
          prerequisites: { all: ["level_43"] },
          unlockableId: Abilities.CHAMPION,
        },
        level_45: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 45,
          prerequisites: { all: ["level_44"] },
          unlockableId: Species.GROUDON,
        },
        level_46: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 46,
          prerequisites: { all: ["level_45"] },
          unlockableId: QuestUnlockables.SHUCKLE_DEFEAT_QUEST,
        },
        level_47: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 47,
          prerequisites: { all: ["level_46"] },
          unlockableId: Abilities.SAND_STREAM,
        },
        level_48: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 48,
          prerequisites: { all: ["level_47"] },
          unlockableId: Abilities.CLUB_CLOBBER,
        },
        level_49: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 49,
          prerequisites: { all: ["level_48"] },
          unlockableId: Species.GEODUDE,
        },
        level_50: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 50,
          prerequisites: { all: ["level_49"] },
          unlockableId: FormChangeItem.BARBARACLITE,
        },
        level_51: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 51,
          prerequisites: { all: ["level_50"] },
          unlockableId: Abilities.SAND_FORCE,
        },
        level_52: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 52,
          prerequisites: { all: ["level_51"] },
          unlockableId: Abilities.GROUND_FLAME,
        },
        level_53: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 53,
          prerequisites: { all: ["level_52"] },
          unlockableId: Species.IRON_TREADS,
        },
        level_54: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 54,
          prerequisites: { all: ["level_53"] },
          unlockableId: QuestUnlockables.CHARIZARD_GROUND_MOVE_KNOCKOUT_QUEST,
        },
        level_55: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 55,
          prerequisites: { all: ["level_54"] },
          unlockableId: Abilities.SAND_RUSH,
        },
        level_56: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 56,
          prerequisites: { all: ["level_55"] },
          unlockableId: Abilities.QUAKER,
        },
        level_57: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 57,
          prerequisites: { all: ["level_56"] },
          unlockableId: Species.BONSLY,
        },
        level_58: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 58,
          prerequisites: { all: ["level_57"] },
          unlockableId: FormChangeItem.TYRANITARITE,
        },
        level_59: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 59,
          prerequisites: { all: ["level_58"] },
          unlockableId: Abilities.ROCKY_PAYLOAD,
        },
        level_60: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 60,
          prerequisites: { all: ["level_59"] },
          unlockableId: Abilities.MUDIATE,
        },
        level_61: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 61,
          prerequisites: { all: ["level_60"] },
          unlockableId: Species.NIHILEGO,
        },
        level_62: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 62,
          prerequisites: { all: ["level_61"] },
          unlockableId: QuestUnlockables.GOLEM_FIRE_QUEST,
        },
        level_63: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 63,
          prerequisites: { all: ["level_62"] },
          unlockableId: Abilities.LEVITATE,
        },
        level_64: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 64,
          prerequisites: { all: ["level_63"] },
          unlockableId: Abilities.BIG_GUTS,
        },
        level_65: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 65,
          prerequisites: { all: ["level_64"] },
          unlockableId: Species.ZUBAT,
        },
        level_66: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 66,
          prerequisites: { all: ["level_65"] },
          unlockableId: FormChangeItem.SKARMORYITE,
        },
        level_67: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 67,
          prerequisites: { all: ["level_66"] },
          unlockableId: Abilities.ARENA_TRAP,
        },
        level_68: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 68,
          prerequisites: { all: ["level_67"] },
          unlockableId: Abilities.METEOR_PROOF,
        },
        level_69: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 69,
          prerequisites: { all: ["level_68"] },
          unlockableId: Species.GREAT_TUSK,
        },
        level_70: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 70,
          prerequisites: { all: ["level_69"] },
          unlockableId: QuestUnlockables.MIMIKYU_REGIROCK_KNOCKOUT_QUEST,
        },
        level_71: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 71,
          prerequisites: { all: ["level_70"] },
          unlockableId: Abilities.EARTH_EATER,
        },
        level_72: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 72,
          prerequisites: { all: ["level_71"] },
          unlockableId: Abilities.SOLID_KONG,
        },
        level_73: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 73,
          prerequisites: { all: ["level_72"] },
          unlockableId: Species.LOTAD,
        },
        level_74: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 74,
          prerequisites: { all: ["level_73"] },
          unlockableId: Abilities.STEADFAST,
        },
        level_75: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 75,
          prerequisites: { all: ["level_74"] },
          unlockableId: Abilities.INTELLY_LECT_ALLY,
        },
        level_76: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 76,
          prerequisites: { all: ["level_75"] },
          unlockableId: Species.STAKATAKA,
        },
        level_77: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 77,
          prerequisites: { all: ["level_76"] },
          unlockableId: QuestUnlockables.FERALIGATOR_ROCK_MOVE_KNOCKOUT_QUEST,
        },
        level_78: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 78,
          prerequisites: { all: ["level_77"] },
          unlockableId: Abilities.DEFIANT,
        },
        level_79: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 79,
          prerequisites: { all: ["level_78"] },
          unlockableId: Abilities.DIRT_THICK,
        },
        level_80: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 80,
          prerequisites: { all: ["level_79"] },
          unlockableId: Species.PINECO,
        },
        level_81: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 81,
          prerequisites: { all: ["level_80"] },
          unlockableId: Abilities.JUSTIFIED,
        },
        level_82: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 82,
          prerequisites: { all: ["level_81"] },
          unlockableId: Abilities.YABA_DABA_DOO,
        },
        level_83: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 83,
          prerequisites: { all: ["level_82"] },
          unlockableId: Species.IRON_BOULDER,
        },
        level_84: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 84,
          prerequisites: { all: ["level_83"] },
          unlockableId: QuestUnlockables.CLAYDOL_POISON_QUEST,
        },
        level_85: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 85,
          prerequisites: { all: ["level_84"] },
          unlockableId: Abilities.GUTS,
        },
        level_86: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 86,
          prerequisites: { all: ["level_85"] },
          unlockableId: Abilities.GOLEM_PLUS,
        },
        level_87: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 87,
          prerequisites: { all: ["level_86"] },
          unlockableId: Abilities.STAMINA,
        },
        level_88: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 88,
          prerequisites: { all: ["level_87"] },
          unlockableId: Abilities.ROCK_FORTRESS,
        },
        level_89: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 89,
          prerequisites: { all: ["level_88"] },
          unlockableId: Abilities.TECHNICIAN,
        },
        level_90: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 90,
          prerequisites: { all: ["level_89"] },
          unlockableId: Abilities.BALANCED_KICK,
        },
        level_91: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 91,
          prerequisites: { all: ["level_90"] },
          unlockableId: Abilities.DIG_CHAMPION,
        },
        level_92: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 92,
          prerequisites: { all: ["level_91"] },
          unlockableId: Abilities.STEADFAST_BULK,
        },
        level_93: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 93,
          prerequisites: { all: ["level_92"] },
          unlockableId: Abilities.SAND_CORRUPTION,
        },
        level_94: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 94,
          prerequisites: { all: ["level_93"] },
          unlockableId: Abilities.MADE_TO_LAST,
        },
      },
    },

    misty: {
      id: "misty",
      type1: Type.WATER,
      trainerType: TrainerType.MISTY,
      ui: {
        previewOffsetY: -25,
        gridOffsetY: -5,
        skillTreeRootOffsetX: 12,
        skillTreeRootOffsetY: -22,
        skillTreeTrainerBondScale: 0.9,
        skillTreeTrainerBondOffsetX: 5,
        skillTreeTrainerBondOffsetY: -7,
      },
      signaturePokemon: [Species.STARYU],
      legendaryPokemon: [Species.SUICUNE],
      pokemonGenerationFilter: [],
      unlockedTMs: [],
      unlockedXMs: [],
      unlockedAbilities: [],
      unlockedSmittyAbilities: [Abilities.MAGICAL_WATER],
      unlockedMegaStones: [FormChangeItem.GYARADOSITE],
      unlockedGlitchForms: ["lavaras"],
      glitchFormUnlockableIds: { "lavaras": QuestUnlockables.LAPRAS_FIRE_MOVE_QUEST },
      unlockedTypeSwitchers: [],
      unlockedEssenceBundles: [],
      unlockedPermaItems: [],
      unlockedStatBoosts: ["misty_speed_boost"],
      unlockedAltBuilds: [PokemonAltBuildId.STARYU_CHRONOS_GEAR],
      unlockedConditionalAbilities: [Abilities.TORRENT],
      unlockedMoveUpgrades: [UpgradePath.ACCURACY_1],
      unlockedTypeBoosters: [],
      unlockedVoucherTiers: [VoucherType.REGULAR, VoucherType.PLUS, VoucherType.PREMIUM],
      unlockedSpecificPermaModifiers: [],
      unlockedTeraTypes: [],
      unlockedMoneyReward: true,
      unlockedPermaMoney: true,
      unlockedBallRaritySelect: { rogue: true, master: true },

      unlockedHealingItems: true,
      unlockedMemoryMushroom: true,
      unlockedBerries: true,
      unlockedAbilitySwitchers: true,
      unlockedGeneralItems: true,
      unlockedBaton: true,
      unlockedPPMax: true,
      unlockedRogueBall: true,
      unlockedGoldenPokeball: true,
      unlockedMasterBall: true,

      unlockRequirements: {
        essenceRequirements: [
          { type: Type.WATER, amount: 200 }
        ],
        totalEssenceRequirement: 200,
        description: () => i18next.t("championSelect:misty.essenceRequirement", { water: 200 })
      },
      lockedSkills: {
        level_1: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 1,
          prerequisites: { all: ["start"] },
          unlockableId: FormChangeItem.SLOWBRONITE,
        },
        level_2: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 2,
          prerequisites: { all: ["level_1"] },
          unlockableId: Abilities.RAIN_DISH,
        },
        level_3: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 3,
          prerequisites: { all: ["level_2"] },
          unlockableId: Abilities.WATER_ABSORB,
        },
        level_4: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 4,
          prerequisites: { all: ["level_3"] },
          unlockableId: Abilities.ABYSSAL_LURE,
        },
        level_5: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 5,
          prerequisites: { all: ["level_4"] },
          unlockableId: Species.VOLCANION,
        },
        level_6: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 6,
          prerequisites: { all: ["level_5"] },
          unlockableId: Abilities.SWIFT_SWIM,
        },
        level_7: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 7,
          prerequisites: { all: ["level_6"] },
          unlockableId: Abilities.ACID_WATER,
        },
        level_8: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 8,
          prerequisites: { all: ["level_7"] },
          unlockableId: Species.HORSEA,
        },
        level_9: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 9,
          prerequisites: { all: ["level_8"] },
          unlockableId: FormChangeItem.STARMITE,
        },
        level_10: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 10,
          prerequisites: { all: ["level_9"] },
          unlockableId: Abilities.DRIZZLE,
        },
        level_11: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 11,
          prerequisites: { all: ["level_10"] },
          unlockableId: Abilities.WATER_POWERED,
        },
        level_12: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 12,
          prerequisites: { all: ["level_11"] },
          unlockableId: Species.LUGIA,
        },
        level_13: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 13,
          prerequisites: { all: ["level_12"] },
          unlockableId: QuestUnlockables.MIMIKYU_GRENINJA_KNOCKOUT_QUEST,
        },
        level_14: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 14,
          prerequisites: { all: ["level_13"] },
          unlockableId: Abilities.STORM_DRAIN,
        },
        level_15: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 15,
          prerequisites: { all: ["level_14"] },
          unlockableId: Abilities.DEEP_SEA_VIRUS,
        },
        level_16: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 16,
          prerequisites: { all: ["level_15"] },
          unlockableId: Species.CORSOLA,
        },
        level_17: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 17,
          prerequisites: { all: ["level_16"] },
          unlockableId: FormChangeItem.STARMITE,
        },
        level_18: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 18,
          prerequisites: { all: ["level_17"] },
          unlockableId: Abilities.WATER_COMPACTION,
        },
        level_19: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 19,
          prerequisites: { all: ["level_18"] },
          unlockableId: Abilities.PHANTOM_TORRENT,
        },
        level_20: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 20,
          prerequisites: { all: ["level_19"] },
          unlockableId: Species.KYOGRE,
        },
        level_21: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 21,
          prerequisites: { all: ["level_20"] },
          unlockableId: QuestUnlockables.MAGIKARP_DEFEAT_QUEST,
        },
        level_22: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 22,
          prerequisites: { all: ["level_21"] },
          unlockableId: Abilities.WATER_BUBBLE,
        },
        level_23: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 23,
          prerequisites: { all: ["level_22"] },
          unlockableId: Abilities.DEADLY_BRINE,
        },
        level_24: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 24,
          prerequisites: { all: ["level_23"] },
          unlockableId: Species.LUVDISC,
        },
        level_25: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 25,
          prerequisites: { all: ["level_24"] },
          unlockableId: FormChangeItem.FERALIGATRITE,
        },
        level_26: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 26,
          prerequisites: { all: ["level_25"] },
          unlockableId: Abilities.SERENE_GRACE,
        },
        level_27: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 27,
          prerequisites: { all: ["level_26"] },
          unlockableId: Abilities.SHINY_SCALE,
        },
        level_28: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 28,
          prerequisites: { all: ["level_27"] },
          unlockableId: Species.WALKING_WAKE,
        },
        level_29: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 29,
          prerequisites: { all: ["level_28"] },
          unlockableId: QuestUnlockables.OCTILLERY_NIGHTMARE_QUEST,
        },
        level_30: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 30,
          prerequisites: { all: ["level_29"] },
          unlockableId: Abilities.CUTE_CHARM,
        },
        level_31: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 31,
          prerequisites: { all: ["level_30"] },
          unlockableId: Abilities.LOVE_POWER,
        },
        level_32: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 32,
          prerequisites: { all: ["level_31"] },
          unlockableId: Species.PSYDUCK,
        },
        level_33: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 33,
          prerequisites: { all: ["level_32"] },
          unlockableId: FormChangeItem.BLASTOISINITE,
        },
        level_34: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 34,
          prerequisites: { all: ["level_33"] },
          unlockableId: Abilities.REGENERATOR,
        },
        level_35: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 35,
          prerequisites: { all: ["level_34"] },
          unlockableId: Abilities.STUBBORN_STANCE,
        },
        level_36: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 36,
          prerequisites: { all: ["level_35"] },
          unlockableId: Species.IRON_BUNDLE,
        },
        level_37: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 37,
          prerequisites: { all: ["level_36"] },
          unlockableId: QuestUnlockables.SQUIRTLE_TORMENT_QUEST,
        },
        level_38: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 38,
          prerequisites: { all: ["level_37"] },
          unlockableId: Abilities.NATURAL_CURE,
        },
        level_39: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 39,
          prerequisites: { all: ["level_38"] },
          unlockableId: Abilities.OMNISCALE,
        },
        level_40: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 40,
          prerequisites: { all: ["level_39"] },
          unlockableId: Species.POLIWAG,
        },
        level_41: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 41,
          prerequisites: { all: ["level_40"] },
          unlockableId: FormChangeItem.GRENINJITE,
        },
        level_42: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 42,
          prerequisites: { all: ["level_41"] },
          unlockableId: Abilities.ADAPTABILITY,
        },
        level_43: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 43,
          prerequisites: { all: ["level_42"] },
          unlockableId: Abilities.SHELL_REPAIR,
        },
        level_44: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 44,
          prerequisites: { all: ["level_43"] },
          unlockableId: Species.KELDEO,
        },
        level_45: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 45,
          prerequisites: { all: ["level_44"] },
          unlockableId: Abilities.QUEENLY_MAJESTY,
        },
        level_46: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 46,
          prerequisites: { all: ["level_45"] },
          unlockableId: Abilities.NEMO_EATER,
        },
        level_47: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 47,
          prerequisites: { all: ["level_46"] },
          unlockableId: Species.GOLDEEN,
        },
        level_48: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 48,
          prerequisites: { all: ["level_47"] },
          unlockableId: FormChangeItem.FERALIGATRITE,
        },
        level_49: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 49,
          prerequisites: { all: ["level_48"] },
          unlockableId: Abilities.MARVEL_SCALE,
        },
        level_50: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 50,
          prerequisites: { all: ["level_49"] },
          unlockableId: Abilities.SCREEN_SWIM,
        },
        level_51: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 51,
          prerequisites: { all: ["level_50"] },
          unlockableId: Species.MANAPHY,
        },
        level_52: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 52,
          prerequisites: { all: ["level_51"] },
          unlockableId: QuestUnlockables.GRENINJA_TRIO_WIN_QUEST,
        },
        level_53: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 53,
          prerequisites: { all: ["level_52"] },
          unlockableId: Abilities.INTIMIDATE,
        },
        level_54: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 54,
          prerequisites: { all: ["level_53"] },
          unlockableId: Abilities.BUBBLING_BRAINS,
        },
        level_55: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 55,
          prerequisites: { all: ["level_54"] },
          unlockableId: Species.AZURILL,
        },
        level_56: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 56,
          prerequisites: { all: ["level_55"] },
          unlockableId: FormChangeItem.SHARPEDONITE,
        },
        level_57: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 57,
          prerequisites: { all: ["level_56"] },
          unlockableId: Abilities.DEFIANT,
        },
        level_58: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 58,
          prerequisites: { all: ["level_57"] },
          unlockableId: Abilities.STEAMIFY,
        },
        level_59: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 59,
          prerequisites: { all: ["level_58"] },
          unlockableId: Species.TAPU_FINI,
        },
        level_60: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 60,
          prerequisites: { all: ["level_59"] },
          unlockableId: QuestUnlockables.LANTURN_NIGHTMARE_QUEST,
        },
        level_61: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 61,
          prerequisites: { all: ["level_60"] },
          unlockableId: Abilities.MEGA_LAUNCHER,
        },
        level_62: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 62,
          prerequisites: { all: ["level_61"] },
          unlockableId: Abilities.SQUIDLY_STEP,
        },
        level_63: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 63,
          prerequisites: { all: ["level_62"] },
          unlockableId: Species.TOGEPI,
        },
        level_64: {
          category: SkillCategory.MEGA_STONES,
          rewardType: SkillTreeRewardType.MEGA_STONE,
          unlockLevel: 64,
          prerequisites: { all: ["level_63"] },
          unlockableId: FormChangeItem.GRENINJITE,
        },
        level_65: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 65,
          prerequisites: { all: ["level_64"] },
          unlockableId: Abilities.SHEER_FORCE,
        },
        level_66: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 66,
          prerequisites: { all: ["level_65"] },
          unlockableId: Abilities.ENHANCED_FOCUS,
        },
        level_67: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 67,
          prerequisites: { all: ["level_66"] },
          unlockableId: Species.PHIONE,
        },
        level_68: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 68,
          prerequisites: { all: ["level_67"] },
          unlockableId: QuestUnlockables.GRENINJA_YOKAI_WAVE_QUEST,
        },
        level_69: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 69,
          prerequisites: { all: ["level_68"] },
          unlockableId: Abilities.STRONG_JAW,
        },
        level_70: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 70,
          prerequisites: { all: ["level_69"] },
          unlockableId: Abilities.DARK_WATERS,
        },
        level_71: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 71,
          prerequisites: { all: ["level_70"] },
          unlockableId: Species.MAGIKARP,
        },
        level_72: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 72,
          prerequisites: { all: ["level_71"] },
          unlockableId: Abilities.LIQUID_VOICE,
        },
        level_73: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 73,
          prerequisites: { all: ["level_72"] },
          unlockableId: Abilities.CHARMING_MIST,
        },
        level_74: {
          category: SkillCategory.LEGENDARY_POKEMON,
          rewardType: SkillTreeRewardType.LEGENDARY_POKEMON,
          unlockLevel: 74,
          prerequisites: { all: ["level_73"] },
          unlockableId: Species.PALKIA,
        },
        level_75: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 75,
          prerequisites: { all: ["level_74"] },
          unlockableId: QuestUnlockables.FERALIGATR_DRAGON_DEFEAT_QUEST,
        },
        level_76: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 76,
          prerequisites: { all: ["level_75"] },
          unlockableId: Abilities.PROPELLER_TAIL,
        },
        level_77: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 77,
          prerequisites: { all: ["level_76"] },
          unlockableId: Abilities.ABYSSAL_AQUA,
        },
        level_78: {
          category: SkillCategory.SIGNATURE_POKEMON,
          rewardType: SkillTreeRewardType.SIGNATURE_POKEMON,
          unlockLevel: 78,
          prerequisites: { all: ["level_77"] },
          unlockableId: Species.CLAUNCHER,
        },
        level_79: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 79,
          prerequisites: { all: ["level_78"] },
          unlockableId: Abilities.ROUGH_SKIN,
        },
        level_80: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 80,
          prerequisites: { all: ["level_79"] },
          unlockableId: Abilities.FRIGHTFUL_CUTE,
        },
        level_81: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 81,
          prerequisites: { all: ["level_80"] },
          unlockableId: QuestUnlockables.BLASTOISE_FAIRY_DEFEAT_QUEST,
        },
        level_82: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 82,
          prerequisites: { all: ["level_81"] },
          unlockableId: Abilities.SNIPER,
        },
        level_83: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 83,
          prerequisites: { all: ["level_82"] },
          unlockableId: Abilities.JELLYFISH_FEVER,
        },
        level_84: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 84,
          prerequisites: { all: ["level_83"] },
          unlockableId: Abilities.TECHNICIAN,
        },
        level_85: {
          category: SkillCategory.SMITTY_ABILITIES,
          rewardType: SkillTreeRewardType.SMITTY_ABILITY,
          unlockLevel: 85,
          prerequisites: { all: ["level_84"] },
          unlockableId: Abilities.NIGHTMARE_INK,
        },
        level_86: {
          category: SkillCategory.GLITCH_FORMS,
          rewardType: SkillTreeRewardType.GLITCH_FORM_UNLOCK,
          unlockLevel: 86,
          prerequisites: { all: ["level_85"] },
          unlockableId: QuestUnlockables.CLOYSTER_PRESENT_QUEST,
        },
        level_87: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 87,
          prerequisites: { all: ["level_86"] },
          unlockableId: Abilities.SKILL_LINK,
        },
        level_88: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 88,
          prerequisites: { all: ["level_87"] },
          unlockableId: Abilities.DRY_SKIN,
        },
        level_89: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 89,
          prerequisites: { all: ["level_88"] },
          unlockableId: Abilities.SURGE_SURFER,
        },
        level_90: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 90,
          prerequisites: { all: ["level_89"] },
          unlockableId: Abilities.ANGER_POINT,
        },
        level_91: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 91,
          prerequisites: { all: ["level_90"] },
          unlockableId: Abilities.STEAM_ENGINE,
        },
        level_92: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 92,
          prerequisites: { all: ["level_91"] },
          unlockableId: Abilities.PIXILATE,
        },
        level_93: {
          category: SkillCategory.TRAINER_BOND_ABILITIES,
          rewardType: SkillTreeRewardType.TRAINER_BOND_ABILITY,
          unlockLevel: 93,
          prerequisites: { all: ["level_92"] },
          unlockableId: Abilities.MISTY_SURGE,
        },
      },
    },
  };
  return _CHAMPION_DEFINITIONS;
}
