export class GameStats {
  public playTime: integer;
  public battles: integer;
  public classicSessionsPlayed: integer;
  public classicSessionsWon: integer;
  public endlessSessionsPlayed: integer;
  public endlessSessionsWon: integer;
  public splicedEndlessSessionsPlayed: integer;
  public splicedEndlessSessionsWon: integer;
  public dailyRunSessionsPlayed: integer;
  public dailyRunSessionsWon: integer;
  public challengeSessionsPlayed: integer;
  public challengeSessionsWon: integer;
  public nuzlockeSessionsPlayed: integer;
  public nuzlockeSessionsWon: integer;
  public draftSessionsPlayed: integer;
  public draftSessionsWon: integer;
  public shopSessionsPlayed: integer;
  public shopSessionsWon: integer;
  public nuzlightSessionsPlayed: integer;
  public nuzlightSessionsWon: integer;
  public nightmareSessionsPlayed: integer;
  public nightmareSessionsWon: integer;
  public nuzlightDraftSessionsPlayed: integer;
  public nuzlightDraftSessionsWon: integer;
  public nuzlockeDraftSessionsPlayed: integer;
  public nuzlockeDraftSessionsWon: integer;
  public testModSessionsPlayed: integer;
  public testModSessionsWon: integer;
  public chaosRogueSessionsPlayed: integer;
  public chaosRogueSessionsWon: integer;
  public chaosJourneySessionsPlayed: integer;
  public chaosJourneySessionsWon: integer;
  public chaosVoidSessionsPlayed: integer;
  public chaosVoidSessionsWon: integer;
  public chaosRogueVoidSessionsPlayed: integer;
  public chaosRogueVoidSessionsWon: integer;
  public chaosInfiniteSessionsPlayed: integer;
  public chaosInfiniteSessionsWon: integer;
  public chaosInfiniteRogueSessionsPlayed: integer;
  public chaosInfiniteRogueSessionsWon: integer;
  public sessionsWon: integer;
  public sessionsPlayed: integer;
  public ribbonsOwned: integer;
  public highestEndlessWave: integer;
  public highestInfiniteWave: integer;
  public highestInfiniteRogueWave: integer;
  public highestLevel: integer;
  public highestMoney: integer;
  public highestPermaMoney: integer;
  public highestDamage: integer;
  public highestHeal: integer;
  public pokemonSeen: integer;
  public pokemonDefeated: integer;
  public pokemonCaught: integer;
  public pokemonHatched: integer;
  public subLegendaryPokemonSeen: integer;
  public subLegendaryPokemonCaught: integer;
  public subLegendaryPokemonHatched: integer;
  public legendaryPokemonSeen: integer;
  public legendaryPokemonCaught: integer;
  public legendaryPokemonHatched: integer;
  public mythicalPokemonSeen: integer;
  public mythicalPokemonCaught: integer;
  public mythicalPokemonHatched: integer;
  public shinyPokemonSeen: integer;
  public shinyPokemonCaught: integer;
  public shinyPokemonHatched: integer;
  public pokemonFused: integer;
  public trainersDefeated: integer;
  public eggsPulled: integer;
  public rareEggsPulled: integer;
  public epicEggsPulled: integer;
  public legendaryEggsPulled: integer;
  public manaphyEggsPulled: integer;
  public rivalsDefeated: integer;
  public glitchFormsUnlocked: integer;
  public smittyFormsUnlocked: integer;
  public fusionsCaptured: integer;
  public glitchEvolutions: integer;
  public smittyEvolutions: integer;
  public dynamaxEvolutions: integer;
  public megaEvolutions: integer;
  public trainerPokemonSnatched: integer;
  public permaItemsBought: integer;
  public glitchFormsDefeated: integer;
  public smittyFormsDefeated: integer;
  public pokeballsThrown: integer;
  public greatballsThrown: integer;
  public ultraballsThrown: integer;
  public rogueballsThrown: integer;
  public masterballsThrown: integer;
  public elite4Defeated: integer;
  public championsDefeated: integer;
  public gruntsDefeated: integer;
  public evilAdminsDefeated: integer;
  public evilBossesDefeated: integer;
  public smittysDefeated: integer;
  public pokemonTradedForMoney: integer;
  public pokemonSwitched: integer;
  public majorBossesDefeated: integer;
  public questsCompleted: integer;
  public bountiesCompleted: integer;
  public battlesEscaped: integer;
  public glitchModsCreated: integer;
  public glitchModsUploaded: integer;
  public glitchModsUnlocked: integer;
  public moneySpentFromSnatching: integer;
  public moneyEarnedFromTrading: integer;
  public totalEvolutions: integer;
  public reroll: integer;
  public permaReroll: integer;
  public modifiersObtained: { [localeKey: string]: integer };
  public typeOfDefeated: { [type: number]: integer };
  public typeOfMovesUsed: { [type: number]: integer };
  public playerKnockoutType: { [type: number]: integer };

  constructor(source?: any) {
    this.playTime = source?.playTime || 0;
    this.battles = source?.battles || 0;
    this.classicSessionsPlayed = source?.classicSessionsPlayed || 0;
    this.classicSessionsWon = source?.classicSessionsWon || source?.sessionsWon || 0;
    this.endlessSessionsPlayed = source?.endlessSessionsPlayed || 0;
    this.endlessSessionsWon = source?.endlessSessionsWon || 0;
    this.splicedEndlessSessionsPlayed = source?.splicedEndlessSessionsPlayed || 0;
    this.splicedEndlessSessionsWon = source?.splicedEndlessSessionsWon || 0;
    this.dailyRunSessionsPlayed = source?.dailyRunSessionsPlayed || 0;
    this.dailyRunSessionsWon = source?.dailyRunSessionsWon || 0;
    this.challengeSessionsPlayed = source?.challengeSessionsPlayed || 0;
    this.challengeSessionsWon = source?.challengeSessionsWon || 0;
    this.nuzlockeSessionsPlayed = source?.nuzlockeSessionsPlayed || 0;
    this.nuzlockeSessionsWon = source?.nuzlockeSessionsWon || 0;
    this.draftSessionsPlayed = source?.draftSessionsPlayed || 0;
    this.draftSessionsWon = source?.draftSessionsWon || 0;
    this.shopSessionsPlayed = source?.shopSessionsPlayed || 0;
    this.shopSessionsWon = source?.shopSessionsWon || 0;
    this.nuzlightSessionsPlayed = source?.nuzlightSessionsPlayed || 0;
    this.nuzlightSessionsWon = source?.nuzlightSessionsWon || 0;
    this.nightmareSessionsPlayed = source?.nightmareSessionsPlayed || 0;
    this.nightmareSessionsWon = source?.nightmareSessionsWon || 0;
    this.nuzlightDraftSessionsPlayed = source?.nuzlightDraftSessionsPlayed || 0;
    this.nuzlightDraftSessionsWon = source?.nuzlightDraftSessionsWon || 0;
    this.nuzlockeDraftSessionsPlayed = source?.nuzlockeDraftSessionsPlayed || 0;
    this.nuzlockeDraftSessionsWon = source?.nuzlockeDraftSessionsWon || 0;
    this.testModSessionsPlayed = source?.testModSessionsPlayed || 0;
    this.testModSessionsWon = source?.testModSessionsWon || 0;
    this.chaosRogueSessionsPlayed = source?.chaosRogueSessionsPlayed || 0;
    this.chaosRogueSessionsWon = source?.chaosRogueSessionsWon || 0;
    this.chaosJourneySessionsPlayed = source?.chaosJourneySessionsPlayed || 0;
    this.chaosJourneySessionsWon = source?.chaosJourneySessionsWon || 0;
    this.chaosVoidSessionsPlayed = source?.chaosVoidSessionsPlayed || 0;
    this.chaosVoidSessionsWon = source?.chaosVoidSessionsWon || 0;
    this.chaosRogueVoidSessionsPlayed = source?.chaosRogueVoidSessionsPlayed || 0;
    this.chaosRogueVoidSessionsWon = source?.chaosRogueVoidSessionsWon || 0;
    this.chaosInfiniteSessionsPlayed = source?.chaosInfiniteSessionsPlayed || 0;
    this.chaosInfiniteSessionsWon = source?.chaosInfiniteSessionsWon || 0;
    this.chaosInfiniteRogueSessionsPlayed = source?.chaosInfiniteRogueSessionsPlayed || 0;
    this.chaosInfiniteRogueSessionsWon = source?.chaosInfiniteRogueSessionsWon || 0;
    this.sessionsWon = source?.sessionsWon || 0;
    this.sessionsPlayed = source?.sessionsPlayed || 0;
    this.ribbonsOwned = source?.ribbonsOwned || 0;
    this.highestEndlessWave = source?.highestEndlessWave || 0;
    this.highestInfiniteWave = source?.highestInfiniteWave || 0;
    this.highestInfiniteRogueWave = source?.highestInfiniteRogueWave || 0;
    this.highestLevel = source?.highestLevel || 0;
    this.highestMoney = source?.highestMoney || 0;
    this.highestPermaMoney = source?.highestPermaMoney || 0;
    this.highestDamage = source?.highestDamage || 0;
    this.highestHeal = source?.highestHeal || 0;
    this.pokemonSeen = source?.pokemonSeen || 0;
    this.pokemonDefeated = source?.pokemonDefeated || 0;
    this.pokemonCaught = source?.pokemonCaught || 0;
    this.pokemonHatched = source?.pokemonHatched || 0;
    this.subLegendaryPokemonSeen = source?.subLegendaryPokemonSeen ?? 0;
    this.subLegendaryPokemonCaught = source?.subLegendaryPokemonCaught ?? 0;
    this.subLegendaryPokemonHatched = source?.subLegendaryPokemonHatched ?? 0;
    this.legendaryPokemonSeen = source?.legendaryPokemonSeen || 0;
    this.legendaryPokemonCaught = source?.legendaryPokemonCaught || 0;
    this.legendaryPokemonHatched = source?.legendaryPokemonHatched || 0;
    this.mythicalPokemonSeen = source?.mythicalPokemonSeen || 0;
    this.mythicalPokemonCaught = source?.mythicalPokemonCaught || 0;
    this.mythicalPokemonHatched = source?.mythicalPokemonHatched || 0;
    this.shinyPokemonSeen = source?.shinyPokemonSeen || 0;
    this.shinyPokemonCaught = source?.shinyPokemonCaught || 0;
    this.shinyPokemonHatched = source?.shinyPokemonHatched || 0;
    this.pokemonFused = source?.pokemonFused || 0;
    this.trainersDefeated = source?.trainersDefeated || 0;
    this.eggsPulled = source?.eggsPulled || 0;
    this.rareEggsPulled = source?.rareEggsPulled || 0;
    this.epicEggsPulled = source?.epicEggsPulled || 0;
    this.legendaryEggsPulled = source?.legendaryEggsPulled || 0;
    this.manaphyEggsPulled = source?.manaphyEggsPulled || 0;
    this.rivalsDefeated = source?.rivalsDefeated || 0;
    this.glitchFormsUnlocked = source?.glitchFormsUnlocked || 0;
    this.smittyFormsUnlocked = source?.smittyFormsUnlocked || 0;
    this.fusionsCaptured = source?.fusionsCaptured || 0;
    this.glitchEvolutions = source?.glitchEvolutions || 0;
    this.smittyEvolutions = source?.smittyEvolutions || 0;
    this.dynamaxEvolutions = source?.dynamaxEvolutions || 0;
    this.megaEvolutions = source?.megaEvolutions || 0;
    this.trainerPokemonSnatched = source?.trainerPokemonSnatched || 0;
    this.permaItemsBought = source?.permaItemsBought || 0;
    this.glitchFormsDefeated = source?.glitchFormsDefeated || 0;
    this.smittyFormsDefeated = source?.smittyFormsDefeated || 0;
    this.pokeballsThrown = source?.pokeballsThrown || 0;
    this.greatballsThrown = source?.greatballsThrown || 0;
    this.ultraballsThrown = source?.ultraballsThrown || 0;
    this.rogueballsThrown = source?.rogueballsThrown || 0;
    this.masterballsThrown = source?.masterballsThrown || 0;
    this.elite4Defeated = source?.elite4Defeated || 0;
    this.championsDefeated = source?.championsDefeated || 0;
    this.gruntsDefeated = source?.gruntsDefeated || 0;
    this.evilAdminsDefeated = source?.evilAdminsDefeated || 0;
    this.evilBossesDefeated = source?.evilBossesDefeated || 0;
    this.smittysDefeated = source?.smittysDefeated || 0;
    this.pokemonTradedForMoney = source?.pokemonTradedForMoney || 0;
    this.pokemonSwitched = source?.pokemonSwitched || 0;
    this.majorBossesDefeated = source?.majorBossesDefeated || 0;
    this.questsCompleted = source?.questsCompleted || 0;
    this.bountiesCompleted = source?.bountiesCompleted || 0;
    this.battlesEscaped = source?.battlesEscaped || 0;
    this.glitchModsCreated = source?.glitchModsCreated || 0;
    this.glitchModsUploaded = source?.glitchModsUploaded || 0;
    this.glitchModsUnlocked = source?.glitchModsUnlocked || 0;
    this.moneySpentFromSnatching = source?.moneySpentFromSnatching || 0;
    this.moneyEarnedFromTrading = source?.moneyEarnedFromTrading || 0;
    this.modifiersObtained = source?.modifiersObtained || {};
    this.totalEvolutions = source?.totalEvolutions || 0;
    this.reroll = source?.reroll || 0;
    this.permaReroll = source?.permaReroll || 0;
    this.typeOfDefeated = source?.typeOfDefeated || {};
    this.typeOfMovesUsed = source?.typeOfMovesUsed || {};
    this.playerKnockoutType = source?.playerKnockoutType || {};
  }
}
