export enum GameMechanicsID {
  CHAOS_MODE,
  COLLECTED_TYPE_MODIFIER,
  CHAMPION_MODE
}

export enum GameMechanicsVersion {
    CHAOS_V1 = "CHAOS_V1_DEBUT",
    CHAOS_V2 = "CHAOS_V2_BALANCE_IMPROVEMENTS",
    COLLECTED_TYPE_MODIFIER_V1 = "COLLECTED_TYPE_OLD_MULTIPLE_MODIFIERS",
    COLLECTED_TYPE_MODIFIER_V2 = "COLLECTED_TYPE_NEW_CONSOLIDATED_MODIFIER",
    PRE_CHAMPION = "PRE_CHAMPION",
    CHAMPION_V1 = "CHAMPION_V1"
}