export enum RewardType {
    GLITCH_FORM_A,
    MODIFIER,
    GAME_MODE,
    UNLOCKABLE,
    GLITCH_FORM_B,
    GLITCH_FORM_C,
    GLITCH_FORM_D,
    GLITCH_FORM_E,
    SMITTY_FORM,
    SMITTY_FORM_B,
    PERMA_MODIFIER,
    PERMA_MONEY,
    PERMA_MONEY_AND_MODIFIER,
    NEW_MOVES_FOR_SPECIES
}