export enum SpeciesFormKey {
    MEGA = "mega",
    MEGA_X = "mega-x",
    MEGA_Y = "mega-y",
    PRIMAL = "primal",
    ORIGIN = "origin",
    INCARNATE = "incarnate",
    THERIAN = "therian",
    GIGANTAMAX = "gigantamax",
    GIGANTAMAX_SINGLE = "gigantamax-single",
    GIGANTAMAX_RAPID = "gigantamax-rapid",
    ETERNAMAX = "eternamax",
    GLITCH = "glitch",
    GLITCH_B = "glitch-b",
    GLITCH_C = "glitch-c",
    GLITCH_D = "glitch-d",
    GLITCH_E = "glitch-e",
    SMITTY = "smitty",
    SMITTY_B = "smitty-b",
    ALT_BUILD = "altbuild"
}